- hosts: role_grand_master
  tasks:
  - name: Get swarm join-token for workers
    shell: docker swarm join-token worker | grep -i 'docker'
    register: join_command_for_workers

  - debug: msg='{{ join_command_for_workers.stdout.strip() }}'
  
  - name: Join workers to swarm
    shell: "{{ join_command_for_workers.stdout.strip() }}}"
    delegate_to: role_worker
    register: result_of_joining

  - debug: msg='{{ result_of_joining.stdout }}'